#!/bin/bash
# chkconfig: 2345 70 80
# description: app script ....

# this script move to /etc/init.d
# must set variable script_home/script_memory

script_home=/opt/script/monitor
script_memory=128M
script=$script_home/start.sh

# See how we were called.
case "$1" in
  start)
        sh $script -h $script_home -m $script_memory -c $1
        ;;
  stop)
        sh $script -h $script_home -c $1
        ;;
  restart|reload)
        sh $script -h $script_home -m $script_memory -c $1
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit

